### PR TITLE
add missing dependencies and codecs for plugins

### PR DESCRIPTION
**Pull request by alexanderadam**

### CODE REVIEW

**Review by apnar — APPROVED** [review]
Thanks for the addition.

**Comment by alexanderadam** [comment]
Wow, you are unbelievable fast!

Thank you for maintaining the Docker image btw! :pray:

**Comment by alexanderadam** [comment]
@apnar could you please activate the issues tab for this repository (`Settings` > check `Issues`)?

**Comment by apnar** [comment]
done

**Pull request merged**
